[package]
name = "openapi_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.29", features = ["derive"] }


openapiv3-extended = "6.0.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
serde_yaml = "0.9.34"
